--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/arrayutils
branches:
  - main
projects:
  arrayutils:
    model: virion
    type: library
    icon: assets/icon.png
    lint:
      phpstan: false
...
